#!/bin/bash
{
echo ""
i="\$(whoami)@\$(uname -n)"
length=\${#i}
after=""
clear
echo "\$i"
while [ \$length -gt 0 ]; do
  after+=-
  length=\$((length-1))
done
echo "\$after"
echo "OS:             \$(uname -o)"
echo "Processor:      \$(uname -p)"
echo "Hardware Info:  \$(uname -m)"
echo "Kernel Name:    \$(uname)"
echo "Kernel Version: \$(uname -v)"
echo "Kernel Release: \$(uname -r)"
} >> ~/.bashrc
