#!/bin/bash
cat <<EOF > /home/$(whoami)/.startup/main
#!/bin/bash
echo "[Writing...]"
{
echo
echo 'i="$(whoami)@$(uname -n)"'
echo 'length=\${#i}'
echo 'after=""'
echo 'clear'
echo 'echo \$i'
echo 'while [ \$length -gt 0 ]; do'
echo '  after+=-'
echo '  length=\$((length-1))'
echo 'done'
echo 'echo \$after'
echo 'echo "OS:             $(uname -o)"'
echo 'echo "Hardware Info:  $(uname -m)"'
echo 'echo "Uptime:         $(( $(printf "%.0f" $(awk '{print $1}' /proc/uptime)) / 60 )) minutes"'
echo 'echo "Kernel Name:    $(uname)"'
echo 'echo "Kernel Version: $(uname -v)"'
echo 'echo "Kernel Release: $(uname -r)"'
} >> ~/.bashrc
echo "[Finished writing to ~/.bashrc]"
EOF
cat <<EOF > /home/$(whoami)/.startup/remove
#!/bin/bash
sudo cp /home/$(whoami)/.startup/bashrc-backup ~/.bashrc
echo "[Restored ~/.bashrc]"
cd /home/$(whoami)
sudo rm -rf /bin/startup
sudo rm -rf /usr/bin/startup
sudo rm -rf .startup
echo "[.startup deleted]"
EOF
sudo chmod +x main
sudo chmod +x remove
echo "[Permissions updated]"
sudo touch /home/$(whoami)/.startup/bashrc-backup
echo "[Backup file created]"
sudo cp ~/.bashrc /home/$(whoami)/.startup/bashrc-backup
echo "[~./bashrc backup written]"
cat <<EOF > /home/$(whoami)/.startup/startupcommand
#!/bin/bash
if [[ \$1 = "-r" ]]; then
  read -p "Are you sure (y/n): " conf
  if [[ \$conf == "y" ]]; then
    cd /home/$(whoami)/.startup
    ./remove
  fi
elif [[ \$1 = "-d" ]]; then
  cp /home/$(whoami)/.startup/bashrc-backup ~/.bashrc
elif [[ \$1 = "-h" ]]; then
  echo "startup [OPTIONS]"
  echo "options:"
  echo "  -h; help"
  echo "  -e; enable     Run the script and show your info on startup"
  echo "  -d; disable    Halt the script and prevent it from running on startup"
  echo "  -r; remove     Remove this script and everything related to it"
  echo "  -u; update     Updates .startup to the newest version"
  echo "  -v; version    Displays the version of .startup"
elif [[ \$1 = "-e" ]]; then
  cd /home/$(whoami)/.startup
  ./main
elif [[ \$1 = "-u" ]]; then 
  cd \$(sudo find /home -type d -name ".startup" -print -quit)
  ./remove
  cd /home/\$(whoami)
  git clone https://github.com/iloveblocks1234/.startup.git
  cd .startup
  sudo chmod +x setup
  ./setup
elif [[ \$1 = "-v" ]]; then
  echo "Versions:"
  echo "  Version 1.0.0; Just the plain command"
  echo "  Version 1.0.1; Added a remove function and a README"
  echo "  Version 1.0.2; Added the command and fixed minor bugs"
  echo "  Version 1.0.3; Fixed the broken v1.1.2"
  echo "  Version 1.0.4; Removed Halt file and replaced with a restore ~/.bashrc command"
  echo "  Dev Version 1.0.5; Improved safety fratures"
  echo "  ___________________________________________"
  echo "  Dev version 1.1.0; Condenced everything into two files"
else
  echo "startup [OPTIONS]"
  echo "options:"
  echo "  -h; help"
  echo "  -e; enable     Run the script and show your info on startup"
  echo "  -d; disable    Halt the script and prevent it from running on startup"
  echo "  -r; remove     Remove this script and everything related to it"
  echo "  -u; update     Updates .startup to the newest version"
  echo "  -v; version    Displays the version of .startup"
fi
EOF
echo "[Command file written]"
sudo cp /home/$(whoami)/.startup/startupcommand /bin/startup
sudo cp /home/$(whoami)/.startup/startupcommand /usr/bin/startup
echo "[Command copied to /bin and /usr/bin]"
sudo chmod +x /bin/startup
sudo chmod +x /usr/bin/startup
echo "[Command permissions updated]"
sudo rm -rf /home/$(whoami)/.startup/startupcommand
echo "[Removed init files]"
echo "'startup -h' for help"
