#!/bin/bash
echo
sudo chmod +x main
sudo chmod +x halt
sudo chmod +x remove
echo "[Permissions updated]"
cat <<EOF > /home/$(whoami)/.startupinfo/startupinfocommand
#!/bin/bash
if [[ \$1 = "-r" ]]; then
  cd \$(sudo find /home -type d -name ".startupinfo" -print -quit)
  ./remove
elif [[ \$1 = "-d" ]]; then
  cd \$(sudo find /home -type d -name ".startupinfo" -print -quit)
  ./halt
elif [[ \$1 = "-h" ]]; then
  echo "startupinfo [OPTIONS]"
  echo "options:"
  echo "  -h; help"
  echo "  -e; enable     Run the script and show your info on startup"
  echo "  -d; disable    Halt the script and prevent it from running on startup"
  echo "  -r; remove     Remove this script and everything related to it"
  echo "  -u; update     Updates .startupinfo to the newest version"
elif [[ \$1 = "-e" ]]; then
  cd \$(sudo find /home -type d -name ".startupinfo" -print -quit)
  ./main
elif [[ \$1 = "-u" ]]; then 
  cd \$(sudo find /home -type d -name ".startupinfo" -print -quit)
  ./remove
  cd /home/$(whoami)
  git clone https://github.com/iloveblocks1234/.startupinfo.git
  cd .startupinfo
  sudo chmod +x setup
  ./setup
fi
EOF
echo "[Command file written]"
sudo cp /home/$(whoami)/.startupinfo/startupinfocommand /bin/startupinfo
sudo cp /home/$(whoami)/.startupinfo/startupinfocommand /usr/bin/startupinfo
echo "[Command copied /bin and /usr/bin]"
sudo chmod +x /bin/startupinfo
sudo chmod +x /usr/bin/startupinfo
echo "[Command permissions updated]"
sudo rm -rf \$(sudo find /home -type d -name "startupinfocommand" -print -quit)
echo "[Removed init files]"
echo
echo "'startupinfo -h' for help"
